#!/bin/bash

#********************************#
#                                #
#    Written by Andras Marton    #
#         July 27, 2019          #
#                                #
*********************************#


for i in $(eval echo {1..$1});do
  subnetmask=$((RANDOM%16+15))
  ip=$(printf "%d.%d.%d.%d\n" "$((RANDOM % 256))" "$((RANDOM % 256))" "$((RANDOM % 256))" "$((RANDOM % 256))") 
  echo $ip "/" $subnetmask
  done
