#!/bin/bash

#********************************#
#                                #
#    Written by Andras Marton    #
#         July 28, 2019          #
#                                #
#********************************#

# Random IP and CIDR subnet mask generator
# v1.1

usage () {
  echo "rand_ip [-h | --help] [-n | --number #]"
}

case $1 in
  -n | --number )
     for i in $(eval echo {1..$2}); do
       subnetmask=$((RANDOM%16+15))
       ip=$(printf "%d.%d.%d.%d" "$((RANDOM % 256))" \
         "$((RANDOM % 256))" "$((RANDOM % 256))" \
         "$((RANDOM % 256))")
       echo $ip"/"$subnetmask
     done
     ;;
  -h | --help )
     usage
     ;;
  * ) 
     usage
     ;;
     esac
